# Generated by Django 4.2.1 on 2023-06-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('items', models.PositiveIntegerField()),
                ('email_adress', models.CharField(max_length=32)),
                ('pick_up_point', models.CharField(max_length=32)),
            ],
        ),
    ]
