# Generated by Django 4.2.1 on 2023-06-21 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='payment',
            new_name='payments',
        ),
    ]
