# Generated by Django 4.2.1 on 2023-06-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email_adress', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=8)),
                ('passsword_confirmation', models.CharField(max_length=8)),
            ],
        ),
    ]
