# Generated by Django 4.2.3 on 2023-07-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_rename_payment_delivery_payments'),
        ('customer', '0001_initial'),
        ('Cart', '0002_cart_delete_delivery'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.delivery'),
        ),
    ]
